server:
    Port: 5005
    RunMode: debug
logger:
    FilePath: ../logs/go.log
    Encoding: json
    level: debug
cors:
    AllowedOrigins: "*"
postgres:
    Host: localhost
    Port: 5432
    User: postgres
    Password: root
    DB_NAME: web_api
    SSLMode: false
redis:
    Host: redis
    Port: 6379
    Password: password
    db: 0
    MinIdleConnections: 100
    PoolSize: 5000
    PoolTimeout: 240
